
server:
    servlet:
        # 한글깨짐 처리 
        encoding:
            force-response: true
    # error:
    #     whitelabel:
    #         enabled: false
    #     path: /errors

# cloud:
#     aws:
#         s3:
#             bucket: mention-bucket.bucket
#         region:
#             static: ap-northeast-2
#             auto: false
#         stack:
#             auto: false
#         credentials:
#             access-key: 
#             secret-key: 

spring:
    output:
        ansi:
            enabled: always
    
    # mustache 설정
    mustache:
        prefix: classpath:templates/
        check-template-location: true
        suffix: .html # .html파일을 모두 mustache으로 인식
        servlet:
            cache: false
    # 데이터베이스 설정 
    datasource:
        url: jdbc:mysql://localhost:3306/nasdaq_db?userSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: hoo
        password: hoo1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    # jpa 설정 
    jpa:
        hibernate:
            ddl-auto: update
            transaction:
                jta:
                    platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect:
                    org.hibernate.dialect.MySQLDialect
   
    sql:
        init:
            platform: mysql
            mode: always
    devtools:
        livereload:
            enabled: true
        freemarker:
            cache: false
        thymeleaf:
            cache: false

springdoc:
  version: 'v1'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /**
    